### ISSUE TITLE
Resampler 的作用，如果只用一层fc+lora效果怎么样？

### ISSUE THREAD

**Issue by double-fire-0** [airaria/Visual-Chinese-LLaMA-Alpaca#5]
想问一下在实验过程中有没有不加resampler的实验，如果只用fc+lora的话结果怎么样呢

**Comment by airaria** [comment]
fc+lora基本上也能训，但效果没有做仔细的评测；
Resampler还起到了压缩图像tokens长度的作用，

**Comment by double-fire-0** [comment]
感谢你的回复
如果只用fc+lora的话和加上resampler相比有什么比较主观的感受嘛

**Comment by GoGoJoestar** [comment]
这个只在前期的时候测过几个例子。从生成文本中出现的图像实体来看，不加resampler和加上resampler对识别图像内容没有太大影响。

**Comment by double-fire-0** [comment]
谢谢🙏！
