### ISSUE TITLE
合并模型

### ISSUE THREAD

**Issue by TJSL0715** [airaria/Visual-Chinese-LLaMA-Alpaca#7]
合并模型时，文本模型--text_model是否可以是原版llama模型合并过Chinese-llama加上Chinese-alpaca的完全模型还是只能是原版llama加上Chinese-alpaca的模型

**Comment by airaria** [comment]
当前版本的模型是基于合并后的chinese-alpaca-plus-7b训练的，
所以这里`--text_model`的原版模型就是llama-7b+chinese-llama-plus-lora-7b+chinese-alpaca-plus-lora-7b合并后的完全模型

**Comment by TJSL0715** [comment]
多谢解答
